"""
This type stub file was generated by pyright.
"""

from ._definitions import __version__
from ._io import count_frames_and_secs, read_frames, write_frames
from ._utils import get_ffmpeg_exe, get_ffmpeg_version

__all__ = [
    "__version__",
    "count_frames_and_secs",
    "read_frames",
    "write_frames",
    "get_ffmpeg_exe",
    "get_ffmpeg_version",
]

""" imageio_ffmpeg, FFMPEG wrapper for Python.
"""
