"""
This type stub file was generated by pyright.
"""

import threading

class LogCatcher(threading.Thread):
    """Thread to keep reading from stderr so that the buffer does not
    fill up and stalls the ffmpeg process. On stderr a message is send
    on every few frames with some meta information. We only keep the
    last ones.
    """
    def __init__(self, file) -> None:
        ...
    
    def stop_me(self) -> None:
        ...
    
    @property
    def header(self) -> str:
        """Get header text. Empty string if the header is not yet parsed."""
        ...
    
    def get_text(self, timeout=...) -> str:
        """Get the whole text written to stderr so far. To preserve
        memory, only the last 50 to 100 frames are kept.

        If a timeout is given, wait for this thread to finish. When
        something goes wrong, we stop ffmpeg and want a full report of
        stderr, but this thread might need a tiny bit more time.
        """
        ...
    
    def run(self) -> None:
        ...
    


def get_output_video_line(lines) -> None:
    """Get the line that defines the video stream that ffmpeg outputs,
    and which we read.
    """
    ...

def limit_lines(lines, N=...):
    """When number of lines > 2*N, reduce to N."""
    ...

def cvsecs(*args) -> float | None:
    """converts a time to second. Either cvsecs(min, secs) or
    cvsecs(hours, mins, secs).
    """
    ...

def parse_ffmpeg_header(text) -> dict[Any, Any]:
    ...

