"""
This type stub file was generated by pyright.
"""

logger = ...
def get_ffmpeg_exe() -> str:
    """
    Get the ffmpeg executable file. This can be the binary defined by
    the IMAGEIO_FFMPEG_EXE environment variable, the binary distributed
    with imageio-ffmpeg, an ffmpeg binary installed with conda, or the
    system ffmpeg (in that order). A RuntimeError is raised if no valid
    ffmpeg could be found.
    """
    ...

def get_ffmpeg_version():
    """
    Get the version of the used ffmpeg executable (as a string).
    """
    ...

