"""
Helper methods for enum types used in the flatbuffer.
Do not modify - generated by ./scripts/gen/enums.py.jinja
"""

from typing import Callable, Final, Literal, NamedTuple


def _normalize_str(value: str) -> str:
    return value.lower().replace("_", "").replace(" ", "")


SamplerType = Literal[
    "DPMPP2MKarras",
    "EulerA",
    "DDIM",
    "PLMS",
    "DPMPPSDEKarras",
    "UniPC",
    "LCM",
    "EulerASubstep",
    "DPMPPSDESubstep",
    "TCD",
    "EulerATrailing",
    "DPMPPSDETrailing",
    "DPMPP2MAYS",
    "EulerAAYS",
    "DPMPPSDEAYS",
    "DPMPP2MTrailing",
    "DDIMTrailing",
    "UniPCTrailing",
    "UniPCAYS",
    "TCDTrailing",
]

SAMPLER_TYPE_VALUES: list[SamplerType] = [
    "DPMPP2MKarras",
    "EulerA",
    "DDIM",
    "PLMS",
    "DPMPPSDEKarras",
    "UniPC",
    "LCM",
    "EulerASubstep",
    "DPMPPSDESubstep",
    "TCD",
    "EulerATrailing",
    "DPMPPSDETrailing",
    "DPMPP2MAYS",
    "EulerAAYS",
    "DPMPPSDEAYS",
    "DPMPP2MTrailing",
    "DDIMTrailing",
    "UniPCTrailing",
    "UniPCAYS",
    "TCDTrailing",
]

_SAMPLER_TYPE_LOOKUP: dict[str, int] = {
    _normalize_str(k): i for i, k in enumerate(SAMPLER_TYPE_VALUES)
}

_SAMPLER_TYPE_DEFAULT = 0


def sampler_type_to_int(value: object) -> int:
    """Return the integer value corresponding to a SamplerType.
    Invalid inputs return the default value (DPMPP2MKarras).
    """
    if value is None:
        return _SAMPLER_TYPE_DEFAULT
    if isinstance(value, int):
        return value if 0 <= value < len(SAMPLER_TYPE_VALUES) else _SAMPLER_TYPE_DEFAULT
    if isinstance(value, str):
        key = _normalize_str(value)
        if (index := _SAMPLER_TYPE_LOOKUP.get(key)) is not None:
            return index
        try:
            int_value = int(key)
            return sampler_type_to_int(int_value)
        except ValueError:
            pass
    return _SAMPLER_TYPE_DEFAULT


def sampler_type_from_value(value: object) -> SamplerType:
    """Return the canonical SamplerType string.
    Invalid inputs return the default value (DPMPP2MKarras).
    """
    index = sampler_type_to_int(value)
    return SAMPLER_TYPE_VALUES[index]


SeedMode = Literal[
    "Legacy",
    "TorchCpuCompatible",
    "ScaleAlike",
    "NvidiaGpuCompatible",
]

SEED_MODE_VALUES: list[SeedMode] = [
    "Legacy",
    "TorchCpuCompatible",
    "ScaleAlike",
    "NvidiaGpuCompatible",
]

_SEED_MODE_LOOKUP: dict[str, int] = {
    _normalize_str(k): i for i, k in enumerate(SEED_MODE_VALUES)
}

_SEED_MODE_DEFAULT = 2


def seed_mode_to_int(value: object) -> int:
    """Return the integer value corresponding to a SeedMode.
    Invalid inputs return the default value (ScaleAlike).
    """
    if value is None:
        return _SEED_MODE_DEFAULT
    if isinstance(value, int):
        return value if 0 <= value < len(SEED_MODE_VALUES) else _SEED_MODE_DEFAULT
    if isinstance(value, str):
        key = _normalize_str(value)
        if (index := _SEED_MODE_LOOKUP.get(key)) is not None:
            return index
        try:
            int_value = int(key)
            return seed_mode_to_int(int_value)
        except ValueError:
            pass
    return _SEED_MODE_DEFAULT


def seed_mode_from_value(value: object) -> SeedMode:
    """Return the canonical SeedMode string.
    Invalid inputs return the default value (ScaleAlike).
    """
    index = seed_mode_to_int(value)
    return SEED_MODE_VALUES[index]


ControlMode = Literal[
    "Balanced",
    "Prompt",
    "Control",
]

CONTROL_MODE_VALUES: list[ControlMode] = [
    "Balanced",
    "Prompt",
    "Control",
]

_CONTROL_MODE_LOOKUP: dict[str, int] = {
    _normalize_str(k): i for i, k in enumerate(CONTROL_MODE_VALUES)
}

_CONTROL_MODE_DEFAULT = 0


def control_mode_to_int(value: object) -> int:
    """Return the integer value corresponding to a ControlMode.
    Invalid inputs return the default value (Balanced).
    """
    if value is None:
        return _CONTROL_MODE_DEFAULT
    if isinstance(value, int):
        return value if 0 <= value < len(CONTROL_MODE_VALUES) else _CONTROL_MODE_DEFAULT
    if isinstance(value, str):
        key = _normalize_str(value)
        if (index := _CONTROL_MODE_LOOKUP.get(key)) is not None:
            return index
        try:
            int_value = int(key)
            return control_mode_to_int(int_value)
        except ValueError:
            pass
    return _CONTROL_MODE_DEFAULT


def control_mode_from_value(value: object) -> ControlMode:
    """Return the canonical ControlMode string.
    Invalid inputs return the default value (Balanced).
    """
    index = control_mode_to_int(value)
    return CONTROL_MODE_VALUES[index]


ControlInputType = Literal[
    "Unspecified",
    "Custom",
    "Depth",
    "Canny",
    "Scribble",
    "Pose",
    "Normalbae",
    "Color",
    "Lineart",
    "Softedge",
    "Seg",
    "Inpaint",
    "Ip2p",
    "Shuffle",
    "Mlsd",
    "Tile",
    "Blur",
    "Lowquality",
    "Gray",
]

CONTROL_INPUT_TYPE_VALUES: list[ControlInputType] = [
    "Unspecified",
    "Custom",
    "Depth",
    "Canny",
    "Scribble",
    "Pose",
    "Normalbae",
    "Color",
    "Lineart",
    "Softedge",
    "Seg",
    "Inpaint",
    "Ip2p",
    "Shuffle",
    "Mlsd",
    "Tile",
    "Blur",
    "Lowquality",
    "Gray",
]

_CONTROL_INPUT_TYPE_LOOKUP: dict[str, int] = {
    _normalize_str(k): i for i, k in enumerate(CONTROL_INPUT_TYPE_VALUES)
}

_CONTROL_INPUT_TYPE_DEFAULT = 0


def control_input_type_to_int(value: object) -> int:
    """Return the integer value corresponding to a ControlInputType.
    Invalid inputs return the default value (Unspecified).
    """
    if value is None:
        return _CONTROL_INPUT_TYPE_DEFAULT
    if isinstance(value, int):
        return (
            value
            if 0 <= value < len(CONTROL_INPUT_TYPE_VALUES)
            else _CONTROL_INPUT_TYPE_DEFAULT
        )
    if isinstance(value, str):
        key = _normalize_str(value)
        if (index := _CONTROL_INPUT_TYPE_LOOKUP.get(key)) is not None:
            return index
        try:
            int_value = int(key)
            return control_input_type_to_int(int_value)
        except ValueError:
            pass
    return _CONTROL_INPUT_TYPE_DEFAULT


def control_input_type_from_value(value: object) -> ControlInputType:
    """Return the canonical ControlInputType string.
    Invalid inputs return the default value (Unspecified).
    """
    index = control_input_type_to_int(value)
    return CONTROL_INPUT_TYPE_VALUES[index]


LoraMode = Literal[
    "All",
    "Base",
    "Refiner",
]

LORA_MODE_VALUES: list[LoraMode] = [
    "All",
    "Base",
    "Refiner",
]

_LORA_MODE_LOOKUP: dict[str, int] = {
    _normalize_str(k): i for i, k in enumerate(LORA_MODE_VALUES)
}

_LORA_MODE_DEFAULT = 0


def lora_mode_to_int(value: object) -> int:
    """Return the integer value corresponding to a LoraMode.
    Invalid inputs return the default value (All).
    """
    if value is None:
        return _LORA_MODE_DEFAULT
    if isinstance(value, int):
        return value if 0 <= value < len(LORA_MODE_VALUES) else _LORA_MODE_DEFAULT
    if isinstance(value, str):
        key = _normalize_str(value)
        if (index := _LORA_MODE_LOOKUP.get(key)) is not None:
            return index
        try:
            int_value = int(key)
            return lora_mode_to_int(int_value)
        except ValueError:
            pass
    return _LORA_MODE_DEFAULT


def lora_mode_from_value(value: object) -> LoraMode:
    """Return the canonical LoraMode string.
    Invalid inputs return the default value (All).
    """
    index = lora_mode_to_int(value)
    return LORA_MODE_VALUES[index]


CompressionMethod = Literal[
    "Disabled",
    "H264",
    "H265",
    "Jpeg",
]

COMPRESSION_METHOD_VALUES: list[CompressionMethod] = [
    "Disabled",
    "H264",
    "H265",
    "Jpeg",
]

_COMPRESSION_METHOD_LOOKUP: dict[str, int] = {
    _normalize_str(k): i for i, k in enumerate(COMPRESSION_METHOD_VALUES)
}

_COMPRESSION_METHOD_DEFAULT = 0


def compression_method_to_int(value: object) -> int:
    """Return the integer value corresponding to a CompressionMethod.
    Invalid inputs return the default value (Disabled).
    """
    if value is None:
        return _COMPRESSION_METHOD_DEFAULT
    if isinstance(value, int):
        return (
            value
            if 0 <= value < len(COMPRESSION_METHOD_VALUES)
            else _COMPRESSION_METHOD_DEFAULT
        )
    if isinstance(value, str):
        key = _normalize_str(value)
        if (index := _COMPRESSION_METHOD_LOOKUP.get(key)) is not None:
            return index
        try:
            int_value = int(key)
            return compression_method_to_int(int_value)
        except ValueError:
            pass
    return _COMPRESSION_METHOD_DEFAULT


def compression_method_from_value(value: object) -> CompressionMethod:
    """Return the canonical CompressionMethod string.
    Invalid inputs return the default value (Disabled).
    """
    index = compression_method_to_int(value)
    return COMPRESSION_METHOD_VALUES[index]


class EnumHelpers(NamedTuple):
    from_value: Callable[[object], str]
    to_int: Callable[[object], int]


EnumTypes = (
    SamplerType
    | SeedMode
    | ControlMode
    | ControlInputType
    | LoraMode
    | CompressionMethod
)

ENUM_HELPER_MAP: Final[dict[str, EnumHelpers]] = {
    "SamplerType": EnumHelpers(sampler_type_from_value, sampler_type_to_int),
    "SeedMode": EnumHelpers(seed_mode_from_value, seed_mode_to_int),
    "ControlMode": EnumHelpers(control_mode_from_value, control_mode_to_int),
    "ControlInputType": EnumHelpers(
        control_input_type_from_value, control_input_type_to_int
    ),
    "LoraMode": EnumHelpers(lora_mode_from_value, lora_mode_to_int),
    "CompressionMethod": EnumHelpers(
        compression_method_from_value, compression_method_to_int
    ),
}

ENUM_TYPE_MAP = {
    "SamplerType": SamplerType,
    "SeedMode": SeedMode,
    "ControlMode": ControlMode,
    "ControlInputType": ControlInputType,
    "LoraMode": LoraMode,
    "CompressionMethod": CompressionMethod,
}
